databases:
  - name: Topathlete15
    databaseName: acto
    user: acto01
    region: Oregon

services:
  - type: web
    name: acto
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: acto
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2